### ISSUE TITLE
Dependency error with python-sat module in Windows

### ISSUE THREAD

**Issue by jmhorcas** [diverso-lab/pysat_metamodel#14]
There is an incompatibility when installing pysat_metamodel due to the version of the python-sat module:
The plugin is trying to install python-sat==0.1.5.dev16 and gets me an error.

However, I can independently install the current version of python-sat (python_sat-0.1.7.dev2) with no error.

I am testing it in Windows. In Linux everything is ok.  This is the only error that raises in Windows.

**Comment by Virako** [comment]
I had talked with @jagalindo  and we will update to python_sat-0.1.7.dev2
