### ISSUE TITLE
Implement the following operations for PySAT:

### ISSUE THREAD

**Issue by jagalindo** [diverso-lab/pysat_metamodel#2]
**Valid Model. This operation checks the semantic correctness of a feature model. This is, if it represents at least one product.
   **Valid Configuration. This operation takes a model and a partial configuration and check if the configuration is correct or not. 
   **Valid Product. This operation takes a product (a.k.a non-partial configuration) and checks its validity on top of the selected model. 
   **All products. This operation print out the list of valid products from a feature model. 
   **Dead Features. This operation detects those features that cannot be selected because of the topology of the model.
   **Core Features. This operation returns the features present in all products.
   **Error diagnosis. This operation returns the possible solutions for the errors present in a model.
   **Error detection. This operation returns a set of errors in a model.

**Comment by jmhorcas** [comment]
### Some help
I needed an implementation of the **ValidConfiguration** operation and implemented it outside the plugin system.
So, here I provide one that I tested:
```
    def execute(self, model: PySATModel) -> 'Glucose3ValidConfiguration':
        g = Glucose3()
        for clause in model.cnf:
            g.add_clause(clause)
        config_names = [feature.name for feature in self.configuration.elements]
        formula = [[clause[0]] if clause[1] in config_names else [-clause[0]] for clause in model.features.items()]
        g.append_formula(formula)
        self.result = g.solve()

        return self
```
After some tries I think this is the most efficient solution by now with complexity **0(n^2 + 2n)** in the worst case (largest configuration) where **n** is the number of features (for both model and configuration).

For the **ValidPartialConfiguration** operation you can use the `assumptions` parameters of the `g.solve()` method to provide the partial configuration.

**Comment by jagalindo** [comment]
I will close this issue as soon as we cross-check the merged content. Anyhow, it looks great to my eyes.

**Comment by jagalindo** [comment]
@jmhorcas you can find the pysat implementation of @GermanMT already merged in the repo. I still need to check the contribution to the core.

**Comment by jmhorcas** [comment]
### The memory leak prolem with Glucose3
The operation analysis with the Glucose3 solver needs to call the "delete()" method of the Glucose3 object in order to destroy it and free the memory used.
This way the solution I proposed for the "valid operation" analysis [here](https://github.com/diverso-lab/pysat_metamodel/issues/2#issuecomment-771560165) can be fixed as follows:

```
    def execute(self, model: PySATModel) -> 'Glucose3ValidConfiguration':
        g = Glucose3()
        for clause in model.cnf:
            g.add_clause(clause)
        config_names = [feature.name for feature in self.configuration.elements]
        formula = [[clause[0]] if clause[1] in config_names else [-clause[0]] for clause in model.features.items()]
        g.append_formula(formula)
        self.result = g.solve()
        g.delete()
        return self
```

**Comment by jagalindo** [comment]
This is only missing the error related operations. @GermanMT as side note, you can take a look to the implementation in https://github.com/jagalindo/A-Python-QX-implementation
