### ISSUE TITLE
Errors in analysis operations when using real feature models

### ISSUE THREAD

**Issue by jmhorcas** [diverso-lab/pysat_metamodel#35]
Several tests fail for some analysis operation using the PYSAT metamodel (https://github.com/diverso-lab/benchmarking/pull/4#issuecomment-966208474), thus those implementation should be revised.
I could take a look to those operations but I am not expert on using SAT solvers.

**Comment by jagalindo** [comment]
There are also some other operations that are failing. Concretly we see that False optional detection and Error diagnosis are returning wrong values (or void) when coping with the integration testsuite and the @jmhorcas real models test suite

![image](https://user-images.githubusercontent.com/1789503/141295931-50c4d630-b484-4c41-9b02-66eab1d5b394.png)

**Comment by jmhorcas** [comment]
Valid, Core, Dead, and False-Optional Features operations seem to be correct now.
I will try to correct the ErrorDiagnosis operation that may require additional information as ocurr with the False-Optional Feature operation.

**Comment by jagalindo** [comment]
An option is to pass some ℹ️ that might be required in the transformation

**Comment by jmhorcas** [comment]
This has been solved completely for some operations, and partially for others (e.g., Error Detection and ErrorDiagnosis needs to be updated to deal with constraints).
