### ISSUE TITLE
use_operation_from_file error when specifying pysat_metamodel as plugin

### ISSUE THREAD

**Issue by pabpazjim** [diverso-lab/pysat_metamodel#47]
When using use_operation_from_file function and specifying pysat_metamodel as plugin_name attribute, it returns this error:

![image](https://user-images.githubusercontent.com/43904563/146537943-fe8ae7bc-55e8-40b4-85f1-2bfc842360bd.png)

This happens only when "pysat_metamodel" is given as plugin_name. With no plugin_name option, any operation which is only supported by pysat runs correctly.

**Comment by jagalindo** [comment]
@Virako is this alredy solved in #78?

**Comment by Virako** [comment]
@jagalindo yes
