### ISSUE TITLE
Error in PySATSatisfiableConfiguration with full configurations

### ISSUE THREAD

**Issue by jmhorcas** [diverso-lab/pysat_metamodel#64]
I found an error in the implementation of this operation:
When working with a full configuration, not matter if your configuration contains features as False, it treats like they were True too.
Looking at the implementation the error is easy to solve (I provide a solution in my next commit) because the implementation of partial and full is slighty different (in the same method). The partial one is correct, the full not.

**Comment by jagalindo** [comment]
That was actually a bug. I was assuming full confs as in fama ts which was a problem. This commit solved the issue so Im clossing the issue
