### ISSUE TITLE
where is the class Feature?

### ISSUE THREAD

**Issue by Virako** [diverso-lab/pysat_metamodel#9]
https://github.com/diverso-lab/pysat_metamodel/blob/9787def51225afb81b4f6c1612d3b6c836af93f9/famapy/metamodels/pysat_metamodel/models/configuration.py#L6

A dict with Featuare as keys and bool as values, it should be defined: dict[Feature, bool], but we need import a Feature class

**Comment by GermanMT** [comment]
If I define the dict as _elementes: dict[Feature,bool]_ importing the Feature class the code throw an exception, the object dict is a 'type' object and cannot be subscriptable

**Comment by Virako** [comment]
My fault. What is your python version? the python version 3.9 permit the use dict or list for hint typing, if the version of python is lower, you need import Dict or List for the hint typing:

from typing import List, Dict
Dict[Feature, bool]

**Comment by GermanMT** [comment]
Actually I'm using the version 3.8.5, now the typing work correctly.
When I create the pull request with the errors found in the test suite how change this, like 3.8 version or 3.9 version?

**Comment by Virako** [comment]
When we started the project, we decided the version 3.8 but I made a mistake because I'm using the version 3.9 and I uploaded some changes with the 3.9 format. The correct version should be the 3.8, but I invoke a @jagalindo for this question.

**Comment by jagalindo** [comment]
I think that starting now on, we can state 3.9 as minimum version
